# Generated by Django 6.0.5 on 2026-05-19 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=60, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Компания')),
                ('niche', models.CharField(blank=True, max_length=160, verbose_name='Ниша')),
                ('package', models.CharField(choices=[('site', 'Сайт за 5 дней'), ('automation', 'Автоматизация продаж'), ('system', 'Система под ключ'), ('bot', 'Бот или скрипт'), ('consult', 'Нужна консультация')], default='consult', max_length=30, verbose_name='Пакет')),
                ('budget', models.CharField(blank=True, max_length=80, verbose_name='Бюджет')),
                ('preferred_contact_time', models.CharField(blank=True, max_length=120, verbose_name='Удобное время')),
                ('message', models.TextField(blank=True, verbose_name='Задача')),
                ('source_path', models.CharField(blank=True, max_length=255, verbose_name='Страница')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Сессия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('qualified', 'Подходит'), ('won', 'Купил'), ('lost', 'Не купил')], db_index=True, default='new', max_length=30, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Клик'), ('package', 'Выбор пакета'), ('form_open', 'Открытие формы'), ('form_submit', 'Отправка формы'), ('call', 'Клик по звонку'), ('messenger', 'Клик по мессенджеру'), ('page_timing', 'Время на странице')], db_index=True, max_length=30, verbose_name='Тип')),
                ('label', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Элемент')),
                ('path', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Страница')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мс')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Сессия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Страница')),
                ('referrer', models.TextField(blank=True, verbose_name='Источник')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Сессия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Устройство')),
                ('status_code', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP статус')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время входа')),
            ],
            options={
                'verbose_name': 'визит',
                'verbose_name_plural': 'визиты',
                'ordering': ['-started_at'],
            },
        ),
    ]
