# Generated by Django 6.0.5 on 2026-05-19 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, unique=True, verbose_name='Telegram chat ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активен')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Владелец')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Telegram админ',
                'verbose_name_plural': 'Telegram админы',
                'ordering': ['-is_owner', '-is_active', 'username', 'chat_id'],
            },
        ),
    ]
