# Generated by Django 6.0.5 on 2026-05-22 10:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_telegramadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Название')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('email', models.EmailField(blank=True, max_length=160, unique=True, verbose_name='Xray email')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'VPN клиент',
                'verbose_name_plural': 'VPN клиенты',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
