# Generated by Django 6.0.5 on 2026-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_vpnclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclient',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Активен до'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='package',
            field=models.CharField(choices=[('p1', 'P1: без лимита + adblock'), ('p2', 'P2: 50 Mbit без adblock'), ('p3', 'P3: 10 Mbit без adblock')], db_index=True, default='p1', max_length=20, verbose_name='Пакет'),
        ),
    ]
